import "./app/select";
import "./app/form";
import "./app/modals";
import "./app/tel-mask";
import "./app/tabs";
import "./app/header-menu";
import "./app/fancybox";
import "./app/slider";
import "./app/text-writing";
import "./app/toggle";
import "./app/temp";
import "./app/menu";
import "./app/counter";
import "./app/contacts";
// import "./app/rent";
// import "./app/filter";
